# Generated by Django 5.1.6 on 2025-02-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='college',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
