# Generated by Django 5.1.6 on 2025-02-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_portfolio_image_portfolio_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
