# Generated by Django 5.1.6 on 2025-03-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='puc_marks',
            field=models.FileField(blank=True, null=True, upload_to='puc_marks/'),
        ),
    ]
