# Generated by Django 5.1.6 on 2025-03-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_portfolio_puc_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='puc_marks',
            field=models.FileField(blank=True, null=True, upload_to='puc_marks/'),
        ),
    ]
