# Generated by Django 5.1.7 on 2026-05-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_alter_portfolio_puc_marks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="puc_marks",
            field=models.FileField(blank=True, null=True, upload_to="puc_marks/"),
        ),
    ]
